name: 🟦 Share MCreator Lore Project Suggestion
description: Suggest something for the MCreator Lore series.
labels: "MCreator Lore"
body:
 - type: textarea
   attributes:
    label: Description
    description: Provide information about your suggestion. The more details the better.
    placeholder: Describe what the suggestion is about.
   validations:
    required: true
