name: 🟪 Share Procedure Project Suggestion
description: Suggest something for a procedure template.
labels: "Procedure Project"
body:
 - type: textarea
   attributes:
    label: Description
    description: Provide information about your suggestion. The more details the better.
    placeholder: Describe what the suggestion is about.
   validations:
    required: true
