name: Tutorial Request
description: Suggest a tutorial for a Minecraft Forge project.
labels: "Tutorial-Request, Submitted"
body:
 - type: textarea
   attributes:
    label: Description
    description: General information about your tutorial request.
    placeholder: Describe what the tutorial would be for.
   validations:
    required: true
 - type: textarea
   attributes:
    label: Features and uses
    description: In point form describe the features you would like me to try adding (Must have at least one feature/use)
    placeholder: |
      1. feature 1
      2. feature 2
      3. feature 3
      ...
   validations:
    required: true
 - type: textarea
   attributes:
    label: Attachments
    description: Provide images or to show an example of what your looking for, if its not based of an exsiting mod or plugin type "n/a" for this box.
    placeholder: |
      Drag and drop images or files onto this box 
      or provide links using \[URL Name](URL PATH)
   validations:
     required: true
 - type: checkboxes
   attributes:
    label: Feature Request tracker rule checks (please read carefully)
    options:
     - label: "I have checked NorthWestTrees Gaming YouTube Channel <a href='https://www.youtube.com/@NorthWestTreesGaming' target='_blank'> MCreator Playlists</a> and it has not been made yet."
       required: true
     - label: "I have checked MCE <a href='https://github.com/orgs/MCreator-Examples/projects/7/views/1?groupedBy%5BcolumnId%5D=Status' target='_blank'>Organaization Projects</a> and the idea has not been suggested yet.</a>"
       required: true
