name: Tutorial Update
description: Request a tutorial to be updated.
labels: "Tutorial-Update, Submitted"
body:
  - type: dropdown
    attributes:
      label: Reason to update the tutorial.
      options:
       - The tutorial has an issue.
       - New feature for the tutorial.
       - Both.
   validations:
     required: true
  - type: textarea
    attributes:
     label: Reason to update
     description: Provide why this tutorial needs to be updated.
     placeholder: The tutorial could be improved with X feature.
    validations:
     required: true
  - type: textarea
    attributes:
     label: Tutorial URL
     description: Provide the link to the existing tutorial on my channel.
     placeholder: YouTube video URL
     validations:
     required: true
  - type: textarea
    attributes:
     label: Attachments
     description: Provide images or to show an example of what your looking for, if its not based of an exsiting mod or plugin type "n/a" for this box.
     placeholder: |
       Drag and drop images or files onto this box 
       or provide links using \[URL Name](URL PATH)
    validations:
      required: false
  - type: checkboxes
    attributes:
     label: Feature Request tracker rule checks (please read carefully)
     options:
      - label: "I have checked NorthWestTrees Gaming YouTube Channel <a href='https://www.youtube.com/@NorthWestTreesGaming' target='_blank'> MCreator Playlists</a> and it has not been made yet."
        required: true
      - label: "I have checked MCE <a href='https://github.com/orgs/MCreator-Examples/projects/7/views/1?groupedBy%5BcolumnId%5D=Status' target='_blank'>Organaization Projects</a> and the idea has not been suggested yet.</a>"
        required: true
